//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackgroundMusic.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackgroundMusic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] black_box_homeplus_129430 {
            get {
                object obj = ResourceManager.GetObject("black-box-homeplus-129430", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] bossa_nova_156936 {
            get {
                object obj = ResourceManager.GetObject("bossa-nova-156936", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PIXABAY LICENSE CERTIFICATE
        ///==============================================
        ///
        ///This document confirms the download of an audio file pursuant to the Content License as defined in the Pixabay Terms of Service available at https://pixabay.com/service/terms/
        ///
        ///Licensor&apos;s Username:
        ///https://pixabay.com/users/music_for_videos-26992513/
        ///
        ///Licensee:
        ///Orpticon
        ///
        ///Audio File Title:
        ///Bossa Nova
        ///
        ///Audio File URL:
        ///https://pixabay.com/music/bossa-nova-bossa-nova-156936/
        ///
        ///Audio File ID:
        ///156936
        ///
        ///Date of download:
        ///2024-04-01 19:16:07  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string bossa_nova_bossa_nova_156936_license {
            get {
                return ResourceManager.GetString("bossa-nova-bossa-nova-156936-license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PIXABAY LICENSE CERTIFICATE
        ///==============================================
        ///
        ///This document confirms the download of an audio file pursuant to the Content License as defined in the Pixabay Terms of Service available at https://pixabay.com/service/terms/
        ///
        ///Licensor&apos;s Username:
        ///https://pixabay.com/users/music_for_videos-26992513/
        ///
        ///Licensee:
        ///Orpticon
        ///
        ///Audio File Title:
        ///Jazz Bossa Nova
        ///
        ///Audio File URL:
        ///https://pixabay.com/music/bossa-nova-jazz-bossa-nova-163669/
        ///
        ///Audio File ID:
        ///163669
        ///
        ///Date of download:
        ///2024-04-01 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string bossa_nova_jazz_bossa_nova_163669_license {
            get {
                return ResourceManager.GetString("bossa-nova-jazz-bossa-nova-163669-license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PIXABAY LICENSE CERTIFICATE
        ///==============================================
        ///
        ///This document confirms the download of an audio file pursuant to the Content License as defined in the Pixabay Terms of Service available at https://pixabay.com/service/terms/
        ///
        ///Licensor&apos;s Username:
        ///https://pixabay.com/users/blackbox-901816/
        ///
        ///Licensee:
        ///Orpticon
        ///
        ///Audio File Title:
        ///BLACK BOX - Homeplus
        ///
        ///Audio File URL:
        ///https://pixabay.com/music/dance-black-box-homeplus-129430/
        ///
        ///Audio File ID:
        ///129430
        ///
        ///Date of download:
        ///2024-04-01 19:15: [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string dance_black_box_homeplus_129430_license {
            get {
                return ResourceManager.GetString("dance-black-box-homeplus-129430-license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] jazz_bossa_nova_163669 {
            get {
                object obj = ResourceManager.GetObject("jazz-bossa-nova-163669", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] pure_energy_3_131087 {
            get {
                object obj = ResourceManager.GetObject("pure-energy-3-131087", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        public static byte[] the_ghost_of_shepardx27s_pie_glbml_112816 {
            get {
                object obj = ResourceManager.GetObject("the-ghost-of-shepardx27s-pie-glbml-112816", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
